language: python
cache: pip
dist: xenial
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install --upgrade coveralls urllib3==1.23 python-dateutil==2.8.0 zipp==1.0.0
  - python setup.py install
# command to run tests
script:
  - python setup.py test
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then coveralls; fi
