language: python
cache: pip
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install --upgrade coveralls
  - python setup.py install
# command to run tests
script:
  - python setup.py test
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then coveralls; fi